project:
  type: website

execute:
  freeze: auto
  
website:
  title: "Work in progress"
  site-url: https://abirks.github.io
  description: "abirks.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects/projects.qmd
        text: Projects
      - icon: github
        href: https://github.com/abirks/
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/absoerensen/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
